from Linked_list import LinkedList
from student import Student


if __name__ == '__main__':
    s1 = Student(1, "Ahmed", "D")
    s2 = Student(2, "mona", "A")
    s3 = Student(3, "ali", "B")
    s4 = Student(4, "Mohamed", "B")
    s5 = Student(5, "nour", 'D')
    s6 = Student(6, "Ramy", "C")
    s7 = Student(7, "hossam", "A")
    s8 = Student(8, "Zyad", 'D')
    ll = LinkedList()
    ll.append(s2)
    ll.append(s3)
    ll.append(s5)
    ll.append(s7)
    ll.insertByPos(0, s1)
    ll.insertByPos(3, s3)
    ll.insertByPos(5, s6)
    ll.insertByPos(7, s8)
    print(f"{' adding ':#^50}")
    print(ll)
    ll.displayAll()
    print(ll.deleteById(1))
    print(f"{' DEL1 ':#^50}")
    ll.displayAll()
    print(ll.deleteById(5))
    print(f"{' DEL5 ':#^50}")
    ll.displayAll()
    ll.deleteById(8)
    print(f"{' DEL8 ':#^50}")
    ll.displayAll()
   
    print(f"{' deleting by group B ':#^50}")
    ll.deleteAllByGroup('B')
    ll.displayAll()
    print(f"{' deleting by group A ':#^50}")
    ll.deleteAllByGroup('A')
    ll.displayAll()
    print(f"{' deleting all ':#^50}")
    ll.deleteAll()
    print(ll)